### ISSUE TITLE
Quasar 1.7.0 crashes when applying the colour widget

### ISSUE THREAD

**Issue by NicoSolALBA** [Quasars/quasar#11]
Živjo Marko & all,

Nicolas from Alba synchrotron there. Tanja Dučić from the MIRAS beamline experiences a reproducible crash of Quasar 1.7.0 everytime she wants to add the Colour widget to her workflows. Please could you help us solving this issue?

Please find afterwards the error description. 
Many thanks

---------------------

Exception:

TypeError: arguments did not match any overloaded call: drawPixmap(self, QRectF, QPixmap, QRectF): argument 1 has unexpected type 'int' drawPixmap(self, QRect, QPixmap, QRect): argument 1 has unexpected type 'int' drawPixmap(self, Union[QPointF, QPoint], QPixmap): argument 1 has unexpected type 'int' drawPixmap(self, QPoint, QPixmap): argument 1 has unexpected type 'int' drawPixmap(self, QRect, QPixmap): argument 1 has unexpected type 'int' drawPixmap(self, int, int, QPixmap): argument 2 has unexpected type 'float' drawPixmap(self, int, int, int, int, QPixmap): argument 2 has unexpected type 'float' drawPixmap(self, int, int, int, int, QPixmap, int, int, int, int): argument 2 has unexpected type 'float' drawPixmap(self, int, int, QPixmap, int, int, int, int): argument 2 has unexpected type 'float' drawPixmap(self, Union[QPointF, QPoint], QPixmap, QRectF): argument 1 has unexpected type 'int' drawPixmap(self, QPoint, QPixmap, QRect): argument 1 has unexpected type 'int'

Module:

Orange.widgets.data.owcolor:438

Version:

1.7.0

Environment:

Python 3.10.8 on Windows 10 10.0.17134 AMD64

Installed Packages:

AnyQt==0.2.0, Bottleneck==1.3.6, CacheControl==0.12.11, Orange-Spectroscopy==0.6.8, Orange3==3.34.1, Pebble==5.0.3, Pillow==9.4.0, PyQt5-Qt5==5.15.2, PyQt5-sip==12.11.0, PyQt5==5.15.7, PyYAML==6.0, Pygments==2.14.0, QtPy==2.3.0, Quasar==1.7.0, XlsxWriter==3.0.7, anyio==3.6.2, asteval==0.9.28, asttokens==2.2.1, backcall==0.2.0, baycomp==1.0.2, certifi==2022.12.7, chardet==5.1.0, charset-normalizer==3.0.1, colorama==0.4.6, colorcet==3.0.1, comm==0.1.2, commonmark==0.9.1, contourpy==1.0.7, cycler==0.11.0, debugpy==1.6.6, decorator==5.1.1, dictdiffer==0.9.0, docutils==0.19, entrypoints==0.4, et-xmlfile==1.1.0, executing==1.2.0, extranormal3==0.0.3, fonttools==4.38.0, future==0.18.3, h11==0.14.0, h5py==3.8.0, httpcore==0.16.3, httpx==0.23.3, idna==3.4, importlib-metadata==6.0.0, ipykernel==6.20.2, ipython-genutils==0.2.0, ipython==8.8.0, jaraco.classes==3.2.3, jedi==0.18.2, joblib==1.2.0, jupyter-client==7.4.9, jupyter-core==5.1.5, keyring==23.13.1, keyrings.alt==4.2.0, kiwisolver==1.4.4, lmfit==1.1.0, lockfile==0.12.2, matplotlib-inline==0.1.6, matplotlib==3.6.3, more-itertools==9.0.0, msgpack==1.0.4, nest-asyncio==1.5.6, networkx==3.0, numpy==1.24.1, openTSNE==0.6.2, openpyxl==3.0.10, opusFC==1.3.0, orange-canvas-core==0.1.29, orange-widget-base==4.19.0, packaging==23.0, pandas==1.5.3, param==1.12.3, parso==0.8.3, pickleshare==0.7.5, pip==22.3.1, platformdirs==2.6.2, prompt-toolkit==3.0.36, psutil==5.9.4, pure-eval==0.2.2, pyct==0.4.8, pyparsing==3.0.9, pyqtgraph==0.13.1, python-dateutil==2.8.2, python-louvain==0.16, pytz==2022.7.1, pywin32-ctypes==0.2.0, pywin32==305, pyzmq==25.0.0, qasync==0.23.0, qtconsole==5.4.0, renishawWiRE==0.1.16, requests==2.28.2, rfc3986==1.5.0, scikit-learn==1.1.3, scipy==1.10.0, serverfiles==0.3.1, setuptools==66.1.1, six==1.16.0, sniffio==1.3.0, spectral==0.23.1, stack-data==0.6.2, threadpoolctl==3.1.0, tornado==6.2, traitlets==5.8.1, typing-extensions==4.4.0, uncertainties==3.1.7, urllib3==1.26.14, wcwidth==0.2.6, wheel==0.38.4, xlrd==2.0.1, zipp==3.11.0

Machine ID:

d855d687-a3ff-4e9a-b897-ab6c899e8be7

Stack Trace:

Traceback (most recent call last):  File "C:\Users\tducic\AppData\Local\miniconda3\envs\quasar\lib\site-packages\Orange\widgets\data\owcolor.py", line 438, in paint    painter.drawPixmap(TypeError: arguments did not match any overloaded call:  drawPixmap(self, QRectF, QPixmap, QRectF): argument 1 has unexpected type 'int'  drawPixmap(self, QRect, QPixmap, QRect): argument 1 has unexpected type 'int'  drawPixmap(self, Union[QPointF, QPoint], QPixmap): argument 1 has unexpected type 'int'  drawPixmap(self, QPoint, QPixmap): argument 1 has unexpected type 'int'  drawPixmap(self, QRect, QPixmap): argument 1 has unexpected type 'int'  drawPixmap(self, int, int, QPixmap): argument 2 has unexpected type 'float'  drawPixmap(self, int, int, int, int, QPixmap): argument 2 has unexpected type 'float'  drawPixmap(self, int, int, int, int, QPixmap, int, int, int, int): argument 2 has unexpected type 'float'  drawPixmap(self, int, int, QPixmap, int, int, int, int): argument 2 has unexpected type 'float'  drawPixmap(self, Union[QPointF, QPoint], QPixmap, QRectF): argument 1 has unexpected type 'int'  drawPixmap(self, QPoint, QPixmap, QRect): argument 1 has unexpected type 'int'

Local Variables:

OrderedDict([('__class__',              <class 'Orange.widgets.data.owcolor.ColorStripDelegate'>),             ('index', <PyQt5.QtCore.QModelIndex object at 0x000001BA7335B060>),             ('option',              <PyQt5.QtWidgets.QStyleOptionViewItem object at 0x000001BA7335B140>),             ('painter', <PyQt5.QtGui.QPainter object at 0x000001BA67F77300>),             ('rect', PyQt5.QtCore.QRect(121, 0, 150, 30)),             ('self',              <Orange.widgets.data.owcolor.ColorStripDelegate object at 0x000001BA6EF697E0>),             ('strip', <PyQt5.QtGui.QPixmap object at 0x000001BA7335A810>)])p, li

**Comment by markotoplak** [comment]
This is solved for new installations.
