### ISSUE TITLE
linux conda bin script has build directory info

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/quasar#7]
In the linux conda quasar package, the `bin/quasar` file starts with
```
#!/Users/marko/opt/miniconda3/conda-bld/quasar_1606838440913/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Quasar==1.0.0','gui_scripts','quasar'
```
which obviously is not a valid interpreter on my (linux) computer :)

**Comment by markotoplak** [comment]
Thanks! Hm, now I am wondering how this can work on Windows (everything uses the same conda package). And funnily, it is a mac path.

**Comment by stuart-cls** [comment]
Just to be clear, this problem comes up for a linux machine.
